### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by clementroche** [darkroomengineering/lenis#287]
### List
- [ ] support pull to refresh and UI collapse on `syncTouch`
- [x] support scroll snap (https://github.com/darkroomengineering/lenis/blob/main/packages/snap/README.md)
- [x] support typescript
- [x] lenis/vue
- [ ] lenis/svelte
- [x] support RSC 'use client'
- [x] listen to overflow change and stop/start accordingly
- [x] include scroll-padding to scrollTo
- [x] auto RAF
- [ ] examples (nested scroll, horizontal, etc.)
- [ ] check if GSAP Scrolltrigger integration is even necessary
- [x] detect internal links (`#anchor`) click and scroll to accordingly
- [ ] deprecate `lenis/snap` `type` option.
- [x] use bun

Breaking changes:
- [ ] rename options correctly (eg: syncTouch -> touch.sync)
- [ ] `lenis/react` deprecate `root` option to not target window but just forward instance. Maybe `children` detection can help.
- [ ] rename properties to be more explicit (eg: isScrolling -> isWheelScrolling/isTouchScrolling/isUserScrolling)
- [ ] `lenis/react` use `useSyncExternalStore`

### How can you help ?

- Pull Requests
- [Become a Sponsor](https://github.com/sponsors/darkroomengineering)

**Comment by Myphz** [comment]
Hello! I see that many types are typed `as any` in dist/types.
Would it be helpful to open a PR and make those types a bit narrower? Or are you working on it already?

**Comment by clementroche** [comment]
@Myphz PR are always welcome

**Comment by Myphz** [comment]
> @Myphz PR are always welcome

I opened https://github.com/darkroomengineering/lenis/pull/345 to improve TypeScript support. Let me know if everything's ok! Thank you

**Comment by giuliobracci** [comment]
Hi @clementroche regarding `rename options correctly (eg: syncTouch -> touch.sync)`, you are talking about renaming and also refactoring the options passed on Lenis instantiation?

E.G:

```
const lenis = new Lenis({
    lerp: 0.1,
    touch: {
     sync: false,
     syncLerp: 0.075,
     inertiaMultiplier: 35
    },
});
```

**Comment by clementroche** [comment]
> Hi @clementroche regarding `rename options correctly (eg: syncTouch -> touch.sync)`, you are talking about renaming and also refactoring the options passed on Lenis instantiation?
> 
> E.G:
> 
> ```
> const lenis = new Lenis({
>     lerp: 0.1,
>     touch: {
>      sync: false,
>      syncLerp: 0.075,
>      inertiaMultiplier: 35
>     },
> });
> ```

Yes @giuliobracci 

```js
const lenis = new Lenis({
    wheel: {
      lerp: 0.1,
    },
    touch: {
     sync: false,
     lerp: 0.075,
     inertiaMultiplier: 35
    },
});
```

**Comment by joebentaylor1995** [comment]
Are we getting rid of snap?

**Comment by clementroche** [comment]
no @joebentaylor1995, it's just about removing `type` option that is legacy stuff
